apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: devops
  labels:
    jenkins: agent
spec:
  containers:
  - name: jenkins-agent
    image: guyedri/elta-agent:latest
    env:
    - name: JENKINS_URL
      value: "http://192.168.49.2:32000"
    - name: JENKINS_AGENT_NAME
      value: "minikube-agent"
    - name: JENKINS_SECRET
      value: "<AGENT_SECRET>"
    resources:
      requests:
        memory: "512Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"

